spring:
  application:
    name: service-registry

eureka:
  server:
    enable-self-preservation: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka